version: '3.9'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-development}  # Use the TARGET environment variable to switch between development and production
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app  # Mount the current directory for hot-reloading in development
      - /app/node_modules  # Avoid overwriting node_modules in development
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - NODE_ENV=${TARGET:-development}  # Pass the environment (development/production)
    command: ${CMD:-pnpm run start:dev}  # Use a default command for development

volumes:
  postgres:
